# Start antigen
source $(brew --prefix)/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle z
antigen bundle jeffreytse/zsh-vi-mode
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme spaceship-prompt/spaceship-prompt

antigen apply
# End antigen

alias cdp="cd ~/Documents/projects"
alias notes="vim ~/Documents/projects/notes"
alias todos="vim ~/Documents/todos"
